workspace:
  base: /go
  path: src/github.com/cjsaylor/jrnl

pipeline:
  test:
    image: cjsaylor/go-alpine-sdk:1.12
    commands:
      - go get -u golang.org/x/tools/cmd/cover
      - go test -cover $(go list ./... | grep -v /vendor/)